In [2]:
import torch

In [ ]:
# 0-D tensor
scalar = torch.tensor(3)   
print(scalar)       # tensor(3)
print(scalar.shape) # torch.Size([])
print(scalar.ndim)  # 0
print(scalar.dtype) # torch.int64

scalar2 = torch.randn(10).sum()
print(scalar2)       # tensor(-0.6778)
print(scalar2.shape) # torch.Size([])
print(scalar2.ndim)  # 0
print(scalar2.dtype) # torch.float32

a = torch.rand((3,4,5))
print(a)
scalar3 = torch.norm(a)
print(scalar3)       # tensor(4.4621)
print(scalar3.shape) # torch.Size([])
print(scalar3.ndim)  # 0
print(scalar3.dtype) # torch.float32

tensor(3)
torch.Size([])
0
torch.int64
tensor(-3.8736)
torch.Size([])
0
torch.float32
tensor([[[0.6464, 0.2190, 0.3491, 0.1715, 0.6927],
         [0.5851, 0.8262, 0.7804, 0.0249, 0.2472],
         [0.7990, 0.6928, 0.7007, 0.9647, 0.5964],
         [0.3987, 0.9602, 0.1992, 0.3600, 0.0203]],

        [[0.9545, 0.3374, 0.1573, 0.5573, 0.6754],
         [0.3582, 0.1536, 0.7443, 0.3852, 0.6371],
         [0.0181, 0.8723, 0.5822, 0.3664, 0.6135],
         [0.0846, 0.2743, 0.4268, 0.8712, 0.1239]],

        [[0.0787, 0.8582, 0.8458, 0.6987, 0.9896],
         [0.4355, 0.4469, 0.0590, 0.6033, 0.0257],
         [0.4188, 0.2952, 0.4162, 0.6849, 0.6183],
         [0.0276, 0.8214, 0.0886, 0.9776, 0.7972]]])
tensor(4.4621)
torch.Size([])
0
torch.float32


In [12]:
# 1-D tensor
vector1 = torch.tensor([1,2,3]) # 0-D tensor가 1,2,3 인 배열
print(vector1)       # tensor([1, 2, 3])
print(vector1.shape) # torch.Size([3])
print(vector1.ndim)  # 1
print(vector1.dtype) # torch.int64

vector2 = torch.randint(5, [1]) # 0-D tensor가 1개인 배열
print(vector2)       # tensor([3]), 0-D 텐서인 tensor(3)과 다름
print(vector2.shape) # torch.Size([1])
print(vector2.ndim)  # 1
print(vector2.dtype) # torch.int64

tensor([1, 2, 3])
torch.Size([3])
1
torch.int64
tensor([4])
torch.Size([1])
1
torch.int64


In [11]:
# 2-D tensor
matrix1 = torch.zeros(3, 4) # 1-D tensor가 3개인 배열
print(matrix1)
print(matrix1.size()) # torch.Size([3, 4])
print(matrix1.dim())  # 2
print(matrix1.dtype)  # torch.float32

matrix2 = torch.eye(4, dtype=torch.double)  # 1-D tensor가 4개인 배열
print(matrix2)
print(matrix2.size()) # torch.Size([4, 4])
print(matrix2.dim())  # 2
print(matrix2.dtype)  # torch.float64

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
2
torch.float32
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=torch.float64)
torch.Size([4, 4])
2
torch.float64


In [16]:
a = torch.randint(10, (2,3,4))
print(a)

# 전체 element 더하여 스칼라 텐서 생성됨, 결과는 0-D tensor
result = a.sum()
print(result)

# dim-0차원 2개의 배열을 더함, 스칼라 탠서로 변하면서 차원이 사라짐 => 결과는 (3,4) shape의 탠서
result = a.sum(dim=0)
print(result)

# dim-1차원 3개의 배열을 더함, 스칼라 텐서로 변하면서 해당 차원이 사라짐 => 결과는 (2,4) shape의 탠서
result = a.sum(dim=1)
print(result)

# dim-2차원 4개의 배열을 더함, 스칼라 텐서로 변하면서 해당 차원이 사라짐 => 결과는 (2,3) shape의 탠서
result = a.sum(dim=2)
print(result)

result = a.sum(dim=-1)
print(result)
result = a.sum(dim=-2)
print(result)
result = a.sum(dim=-3)
print(result)
                

tensor([[[4, 3, 4, 3],
         [5, 0, 1, 3],
         [3, 6, 8, 6]],

        [[5, 3, 2, 1],
         [1, 5, 0, 4],
         [2, 0, 1, 6]]])
tensor(76)
tensor([[ 9,  6,  6,  4],
        [ 6,  5,  1,  7],
        [ 5,  6,  9, 12]])
tensor([[12,  9, 13, 12],
        [ 8,  8,  3, 11]])
tensor([[14,  9, 23],
        [11, 10,  9]])
tensor([[14,  9, 23],
        [11, 10,  9]])
tensor([[12,  9, 13, 12],
        [ 8,  8,  3, 11]])
tensor([[ 9,  6,  6,  4],
        [ 6,  5,  1,  7],
        [ 5,  6,  9, 12]])


In [6]:
import torch

a = torch.randn(2, 3)
print(a)
b = torch.randn(2, 3)
print(b)
# 2-D tensor + 2-D tensor
print(a + b)
print(torch.add(a, b))
# 2-D tensor - 2-D tensor
print(a - b)
print(torch.sub(a, b))
# 2-D tensor * 2-D tensor
print(a * b)
print(torch.mul(a, b))
# 2-D tensor / 2-D tensor
print(a / b)
print(torch.div(a, b))  

tensor([[-0.3650,  0.9625, -1.2006],
        [-0.3323, -1.2849,  1.1461]])
tensor([[-0.7497, -1.4571,  0.6495],
        [-1.5047, -0.9088, -0.8864]])
tensor([[-1.1147, -0.4946, -0.5511],
        [-1.8370, -2.1937,  0.2597]])
tensor([[-1.1147, -0.4946, -0.5511],
        [-1.8370, -2.1937,  0.2597]])
tensor([[ 0.3848,  2.4196, -1.8501],
        [ 1.1724, -0.3761,  2.0325]])
tensor([[ 0.3848,  2.4196, -1.8501],
        [ 1.1724, -0.3761,  2.0325]])
tensor([[ 0.2736, -1.4025, -0.7798],
        [ 0.5000,  1.1677, -1.0159]])
tensor([[ 0.2736, -1.4025, -0.7798],
        [ 0.5000,  1.1677, -1.0159]])
tensor([[ 0.4868, -0.6605, -1.8485],
        [ 0.2208,  1.4138, -1.2930]])
tensor([[ 0.4868, -0.6605, -1.8485],
        [ 0.2208,  1.4138, -1.2930]])


In [5]:
import torch

# 행렬곱
a = torch.randn(2, 3)
print(a)
b = torch.randn(3, 4)
print(b)
# 2-D tensor @ 2-D tensor
print(a @ b)
print(torch.matmul(a, b))
# 2-D tensor . 2-D tensor
print(a.mm(b))
print(torch.mm(a, b))   

tensor([[-0.3465, -0.0053, -0.3504],
        [-1.0029, -1.8632, -1.8125]])
tensor([[ 1.1456,  1.3126,  1.2783, -0.5436],
        [-1.2600, -0.0510,  0.4871, -0.6189],
        [-0.0483, -1.5231, -0.7121, -1.5880]])
tensor([[-0.3734,  0.0792, -0.1960,  0.7481],
        [ 1.2864,  1.5395, -0.8988,  4.5766]])
tensor([[-0.3734,  0.0792, -0.1960,  0.7481],
        [ 1.2864,  1.5395, -0.8988,  4.5766]])
tensor([[-0.3734,  0.0792, -0.1960,  0.7481],
        [ 1.2864,  1.5395, -0.8988,  4.5766]])
tensor([[-0.3734,  0.0792, -0.1960,  0.7481],
        [ 1.2864,  1.5395, -0.8988,  4.5766]])


In [38]:
# 공용함수, 삼각함수, 지수함수, 로그함수, 비교함수, 논리함수, 통계함수, 선형대수 함수 등
a = torch.randn(2, 3)
print(a)    
print(torch.abs(a))        # 절댓값
print(torch.acos(a))       # 아크코사인
print(torch.asin(a))       # 아크사인
print(torch.atan(a))       # 아크탄젠트
print(torch.ceil(a))       # 올림
print(torch.clamp(a, min=0.0)) # 최소값 지정
print(torch.cos(a))        # 코사인
print(torch.cosh(a))       # 쌍곡코사인
print(torch.exp(a))        # 지수함수
print(torch.floor(a))      # 내림
print(torch.log(a))        # 자연로그
print(torch.log10(a))      # 상용로그
print(torch.log2(a))       # 이진로그
print(torch.neg(a))        # 음수
print(torch.reciprocal(a)) # 역수
print(torch.round(a))      # 반올림
print(torch.rsqrt(a))      # 역수의 제곱근
print(torch.sign(a))       # 부호
print(torch.sin(a))        # 사인
print(torch.sinh(a))       # 쌍곡사인
print(torch.sqrt(a))       # 제곱근
print(torch.tan(a))        # 탄젠트
print(torch.tanh(a))       # 쌍곡탄젠트
print(torch.trunc(a))      # 정수부분
print(torch.eq(a, 0.0))    # 요소별 동일여부
print(torch.ge(a, 0.0))    # 요소별 크거나 같은지 여부
print(torch.gt(a, 0.0))    # 요소별 큰지 여부
print(torch.le(a, 0.0))    # 요소별 작거나 같은지 여부
print(torch.lt(a, 0.0))    # 요소별 작은지 여부
print(torch.ne(a, 0.0))    # 요소별 같지 않은지 여부
print(torch.all(a))        # 모든 요소가 참인지 여부
print(torch.any(a))        # 하나 이상의 요소가 참인지 여부
print(torch.argmax(a))     # 가장 큰 요소의 인덱스
print(torch.argmin(a))     # 가장 작은 요소의 인덱스
print(torch.max(a))        # 가장 큰 요소
print(torch.min(a))        # 가장 작은 요소
print(torch.mean(a))       # 평균
print(torch.median(a))     # 중앙값
print(torch.mode(a))       # 최빈값
print(torch.std(a))        # 표준편차
print(torch.var(a))        # 분산
print(torch.sum(a))        # 합 
print(torch.prod(a))       # 곱
print(torch.cumsum(a, dim=0)) # 누적합
print(torch.cumprod(a, dim=0))# 누적곱
print(torch.sort(a, dim=0))   # 정렬
print(torch.argsort(a, dim=0))# 정렬된 인덱스
print(torch.unique(a))        # 중복제거
print(torch.where(a>0, a, -a))# 조건에 따라 값 선택
print(torch.nonzero(a))      # 0이 아닌 요소의 인덱스
         

tensor([[-0.6627,  2.4958,  3.0296],
        [-0.5729, -0.0777, -0.3991]])
tensor([[0.6627, 2.4958, 3.0296],
        [0.5729, 0.0777, 0.3991]])
tensor([[2.2952,    nan,    nan],
        [2.1808, 1.6486, 1.9813]])
tensor([[-0.7244,     nan,     nan],
        [-0.6101, -0.0778, -0.4105]])
tensor([[-0.5852,  1.1897,  1.2520],
        [-0.5203, -0.0776, -0.3797]])
tensor([[-0., 3., 4.],
        [-0., -0., -0.]])
tensor([[0.0000, 2.4958, 3.0296],
        [0.0000, 0.0000, 0.0000]])
tensor([[ 0.7883, -0.7987, -0.9937],
        [ 0.8403,  0.9970,  0.9214]])
tensor([[ 1.2277,  6.1072, 10.3687],
        [ 1.1687,  1.0030,  1.0807]])
tensor([[ 0.5155, 12.1320, 20.6890],
        [ 0.5639,  0.9252,  0.6709]])
tensor([[-1.,  2.,  3.],
        [-1., -1., -1.]])
tensor([[   nan, 0.9146, 1.1084],
        [   nan,    nan,    nan]])
tensor([[   nan, 0.3972, 0.4814],
        [   nan,    nan,    nan]])
tensor([[   nan, 1.3195, 1.5991],
        [   nan,    nan,    nan]])
tensor([[ 0.6627, -2.4958, -3.0296],

In [58]:
a = torch.randint(9, (2, 3))
b = torch.randint(9, (2, 3))
print("-"*20)
c = a.logical_and(b) # 요소별 논리 AND
print(c)
c = a.logical_or(b)  # 요소별 논리 OR
print(c)
c = c.logical_not()  # 요소별 논리 NOT  
print(c)

--------------------
tensor([[ True,  True,  True],
        [False,  True,  True]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [ ]:
# 텐서 변형 함수
a = torch.randn(2, 3)
print(a)

print(torch.flatten(a))      # 다차원 텐서를 1-D tensor로 변환
print(torch.reshape(a, (3,2))) # 텐서의 shape 변경
print(torch.transpose(a, 0, 1)) # 텐서의 차원 교환
print(torch.t(a))            # 2-D tensor의 전치행렬
print(torch.unsqueeze(a, 0)) # 지정한 위치에 차원 추가
print(torch.unsqueeze(a, 1)) # 지정한 위치에 차원 추가
print(torch.unsqueeze(a, 2)) # 지정한 위치에 차원 추가
print(torch.squeeze(a))      # 크기가 1인 차원 제거
print(torch.squeeze(torch.unsqueeze(a, 0))) # 크기가 1인 차원 제거

tensor([[-1.5821,  0.0827, -1.6979],
        [-1.4800,  0.0581, -0.3157]])
tensor([-1.5821,  0.0827, -1.6979, -1.4800,  0.0581, -0.3157])
tensor([[-1.5821,  0.0827],
        [-1.6979, -1.4800],
        [ 0.0581, -0.3157]])
tensor([[-1.5821, -1.4800],
        [ 0.0827,  0.0581],
        [-1.6979, -0.3157]])
tensor([[-1.5821, -1.4800],
        [ 0.0827,  0.0581],
        [-1.6979, -0.3157]])
tensor([[[-1.5821,  0.0827, -1.6979],
         [-1.4800,  0.0581, -0.3157]]])
tensor([[[-1.5821,  0.0827, -1.6979]],

        [[-1.4800,  0.0581, -0.3157]]])
tensor([[[-1.5821],
         [ 0.0827],
         [-1.6979]],

        [[-1.4800],
         [ 0.0581],
         [-0.3157]]])
tensor([[-1.5821,  0.0827, -1.6979],
        [-1.4800,  0.0581, -0.3157]])
tensor([[-1.5821,  0.0827, -1.6979],
        [-1.4800,  0.0581, -0.3157]])


In [ ]:
# 텐서 결합 함수 cat

a = torch.randint(9, (2, 3))
print(a)

print("-"*20)
b = torch.cat([a, a], dim=0)  # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)
b = torch.cat([a, a], dim=1) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)

tensor([[0, 4, 6],
        [1, 2, 2]])
--------------------
tensor([[0, 4, 6],
        [1, 2, 2],
        [0, 4, 6],
        [1, 2, 2]])
torch.Size([4, 3])
--------------------
tensor([[0, 4, 6, 0, 4, 6],
        [1, 2, 2, 1, 2, 2]])
torch.Size([2, 6])
--------------------


In [ ]:
import torch

# 텐서 결합 함수 stack
a = torch.randint(9, (3,4))
print(a)
print(a.shape)
print("-"*20)
b = torch.stack([a, a], dim=0) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)
b = torch.stack([a, a], dim=1) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)
b = torch.stack([a, a], dim=2) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)

tensor([[2, 3, 7, 2],
        [4, 8, 6, 2],
        [7, 2, 1, 4]])
torch.Size([3, 4])
--------------------
tensor([[[2, 3, 7, 2],
         [4, 8, 6, 2],
         [7, 2, 1, 4]],

        [[2, 3, 7, 2],
         [4, 8, 6, 2],
         [7, 2, 1, 4]]])
torch.Size([2, 3, 4])
--------------------
tensor([[[2, 3, 7, 2],
         [2, 3, 7, 2]],

        [[4, 8, 6, 2],
         [4, 8, 6, 2]],

        [[7, 2, 1, 4],
         [7, 2, 1, 4]]])
torch.Size([3, 2, 4])
--------------------
tensor([[[2, 2],
         [3, 3],
         [7, 7],
         [2, 2]],

        [[4, 4],
         [8, 8],
         [6, 6],
         [2, 2]],

        [[7, 7],
         [2, 2],
         [1, 1],
         [4, 4]]])
torch.Size([3, 4, 2])
--------------------


In [ ]:
# tensor가 아닌 Python 기본 타입을 출력하는 경우
a = torch.tensor([3.5])
print(a)
print(a.item())  # 스칼라 텐서의 값을 Python 기본 타입으로 반환 

#크기/차원 정보
print(a.shape) # torch.Size([1])
print(a.ndim)  # 1
print(a.dtype) # torch.float32  
print(a.numel()) # 1, 텐서의 모든 요소 개수

# 전체 동등성 검사
b = torch.tensor([2.5])
print(a.equal(b))  # False
print(a == b)      # tensor([False])


tensor([3.5000])
3.5
torch.Size([1])
1
torch.float32
1
False
tensor([False])


In [60]:
# 일부 검사함수
a = torch.randint(9, (2, 3))
print(a)   
b = a.is_floating_point() # 실수형 여부
print(b)
b = a.is_complex()       # 복소수형 여부
print(b)
b = a.is_same_size(a)    # 동일한 shape인지 여부
print(b)    
b = a.is_contiguous()    # 메모리상에 연속적으로 저장되어 있는지 여부
print(b) 

tensor([[8, 7, 8],
        [3, 5, 8]])
False
False
True
True


In [67]:
a = torch.rand((2, 3))
print(a)

b = a.norm(p=2, dim=0) # 열벡터의 L2 norm 계산
print(b)
b = a.norm(p=2, dim=1) # 행벡터의 L2 norm 계산
print(b)

tensor([[0.8597, 0.4340, 0.8291],
        [0.2461, 0.3508, 0.7779]])
tensor([0.8943, 0.5581, 1.1369])
tensor([1.2708, 0.8881])


In [ ]:
from sklearn.preprocessing import StandardScaler

X = torch.randn(5, 3).numpy() # 5개의 샘플과 3개의 특성
y = torch.randn(5).numpy()    # 5개의 샘플에 대한 타겟 값

# X에 적용할 scaler 객체 생성
scaler = StandardScaler().fit(X)
# y에 적용할 scaler 객체 생성
scaler_y = StandardScaler().fit(y.reshape(-1, 1))
# X에 transform 적용
X_scaled = scaler.transform(X)
# y에 transform 적용
y_scaled = scaler_y.transform(y.reshape(-1, 1)) 




[[-0.19453548 -1.4225612  -0.35592303]
 [ 1.2291666   0.85571223  1.7130218 ]
 [ 0.8321378   0.37036565  0.13470927]
 [-1.6462796  -0.92342424 -0.1103007 ]
 [-0.2204894   1.1199076  -1.3815073 ]]
[[ 0.74191433]
 [ 0.5432975 ]
 [-1.7916003 ]
 [ 0.8920779 ]
 [-0.38568944]]
(5, 3)
(5, 1)


In [72]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

mm = MinMaxScaler()
a = torch.rand((2,3))
print(a)
b = mm.fit_transform(a)
print(b)

norm = Normalizer(norm='l2')
a = torch.rand((2,3))
print(a)
b = norm.fit_transform(a)
print(b)
print(torch.norm(torch.tensor(b), p=2, dim=1))  # 행벡터의 L2 norm 계산, 모두 1.0이 나옴


tensor([[0.1342, 0.2758, 0.0850],
        [0.7979, 0.9123, 0.5614]])
[[0. 0. 0.]
 [1. 1. 1.]]
tensor([[0.4099, 0.1707, 0.4768],
        [0.3294, 0.6081, 0.0331]])
[[0.629098   0.26206008 0.73181987]
 [0.47580564 0.8782536  0.0477452 ]]
tensor([1.0000, 1.0000])
