In [1]:
import torch

# 0-D tensor
scalar = torch.tensor(3)   
print(scalar)       # tensor(3)
print(scalar.shape) # torch.Size([])
print(scalar.ndim)  # 0
print(scalar.dtype) # torch.int64

scalar2 = torch.randn(10).sum()
print(scalar2)       # tensor(-0.6778)
print(scalar2.shape) # torch.Size([])
print(scalar2.ndim)  # 0
print(scalar2.dtype) # torch.float32

a = torch.rand((3,4,5))
print(a)
scalar3 = torch.norm(a)
print(scalar3)       # tensor(4.4621)
print(scalar3.shape) # torch.Size([])
print(scalar3.ndim)  # 0
print(scalar3.dtype) # torch.float32

tensor(3)
torch.Size([])
0
torch.int64
tensor(0.9743)
torch.Size([])
0
torch.float32
tensor([[[0.1467, 0.4434, 0.9087, 0.5954, 0.1605],
         [0.0402, 0.3145, 0.9023, 0.8484, 0.9718],
         [0.8680, 0.0204, 0.2247, 0.2975, 0.7184],
         [0.1576, 0.5459, 0.3565, 0.4674, 0.8257]],

        [[0.7014, 0.9176, 0.4764, 0.9492, 0.1552],
         [0.4160, 0.9869, 0.4227, 0.5630, 0.3277],
         [0.5064, 0.4672, 0.5825, 0.7038, 0.1556],
         [0.6259, 0.5236, 0.2598, 0.3897, 0.6022]],

        [[0.8604, 0.4190, 0.8576, 0.0168, 0.6593],
         [0.6359, 0.7755, 0.0363, 0.1991, 0.2901],
         [0.4251, 0.4488, 0.8984, 0.0887, 0.7027],
         [0.3214, 0.8758, 0.6163, 0.4674, 0.3753]]])
tensor(4.4830)
torch.Size([])
0
torch.float32


In [1]:
import torch

# 1-D tensor
vector1 = torch.tensor([1,2,3]) # 0-D tensor가 1,2,3 인 배열
print(vector1)       # tensor([1, 2, 3])
print(vector1.shape) # torch.Size([3])
print(vector1.ndim)  # 1
print(vector1.dtype) # torch.int64

vector2 = torch.randint(5, [1]) # 0-D tensor가 1개인 배열
print(vector2)       # tensor([3]), 0-D 텐서인 tensor(3)과 다름
print(vector2.shape) # torch.Size([1])
print(vector2.ndim)  # 1
print(vector2.dtype) # torch.int64

tensor([1, 2, 3])
torch.Size([3])
1
torch.int64
tensor([1])
torch.Size([1])
1
torch.int64


In [5]:
# 2-D tensor
matrix1 = torch.zeros(3, 4) # 1-D tensor가 3개인 배열
print(matrix1)
print(matrix1.size()) # torch.Size([3, 4])
print(matrix1.dim())  # 2
print(matrix1.dtype)  # torch.float32

matrix2 = torch.eye(4, dtype=torch.double)  # 1-D tensor가 4개인 배열
print(matrix2)
print(matrix2.size()) # torch.Size([4, 4])
print(matrix2.dim())  # 2
print(matrix2.dtype)  # torch.float64

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
2
torch.float32
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=torch.float64)
torch.Size([4, 4])
2
torch.float64


In [3]:
import torch

a = torch.randint(10, (2,3,4))
print(a)

# 전체 element 더하여 스칼라 텐서 생성됨, 결과는 0-D tensor
result = a.sum()
print(result)

# dim-0차원 2개의 배열을 더함, 스칼라 탠서로 변하면서 차원이 사라짐 => 결과는 (3,4) shape의 탠서
result = a.sum(dim=0)
print(result)

# dim-1차원 3개의 배열을 더함, 스칼라 텐서로 변하면서 해당 차원이 사라짐 => 결과는 (2,4) shape의 탠서
result = a.sum(dim=1)
print(result)

# dim-2차원 4개의 배열을 더함, 스칼라 텐서로 변하면서 해당 차원이 사라짐 => 결과는 (2,3) shape의 탠서
result = a.sum(dim=2)
print(result)

result = a.sum(dim=-1)
print(result)
result = a.sum(dim=-2)
print(result)
result = a.sum(dim=-3)
print(result)
                

tensor([[[9, 6, 1, 8],
         [7, 8, 3, 9],
         [4, 3, 5, 5]],

        [[1, 0, 9, 0],
         [7, 2, 0, 1],
         [9, 6, 9, 4]]])
tensor(116)
tensor([[10,  6, 10,  8],
        [14, 10,  3, 10],
        [13,  9, 14,  9]])
tensor([[20, 17,  9, 22],
        [17,  8, 18,  5]])
tensor([[24, 27, 17],
        [10, 10, 28]])
tensor([[24, 27, 17],
        [10, 10, 28]])
tensor([[20, 17,  9, 22],
        [17,  8, 18,  5]])
tensor([[10,  6, 10,  8],
        [14, 10,  3, 10],
        [13,  9, 14,  9]])


In [7]:
import torch

a = torch.randn(2, 3)
print(a)
b = torch.randn(2, 3)
print(b)
# 2-D tensor + 2-D tensor
print(a + b)
print(torch.add(a, b))
# 2-D tensor - 2-D tensor
print(a - b)
print(torch.sub(a, b))
# 2-D tensor * 2-D tensor
print(a * b)
print(torch.mul(a, b))
# 2-D tensor / 2-D tensor
print(a / b)
print(torch.div(a, b))  

tensor([[-1.5279, -0.7217, -0.0417],
        [ 0.6262, -0.8656,  1.1461]])
tensor([[ 0.4970, -0.3481,  0.4370],
        [ 1.0724,  0.6319,  1.2457]])
tensor([[-1.0309, -1.0699,  0.3954],
        [ 1.6986, -0.2337,  2.3918]])
tensor([[-1.0309, -1.0699,  0.3954],
        [ 1.6986, -0.2337,  2.3918]])
tensor([[-2.0249, -0.3736, -0.4787],
        [-0.4462, -1.4975, -0.0996]])
tensor([[-2.0249, -0.3736, -0.4787],
        [-0.4462, -1.4975, -0.0996]])
tensor([[-0.7593,  0.2513, -0.0182],
        [ 0.6715, -0.5470,  1.4277]])
tensor([[-0.7593,  0.2513, -0.0182],
        [ 0.6715, -0.5470,  1.4277]])
tensor([[-3.0742,  2.0731, -0.0953],
        [ 0.5839, -1.3698,  0.9201]])
tensor([[-3.0742,  2.0731, -0.0953],
        [ 0.5839, -1.3698,  0.9201]])


In [8]:
import torch

# 행렬곱
a = torch.randn(2, 3)
print(a)
b = torch.randn(3, 4)
print(b)
# 2-D tensor @ 2-D tensor
print(a @ b)
print(torch.matmul(a, b))
# 2-D tensor . 2-D tensor
print(a.mm(b))
print(torch.mm(a, b))   

tensor([[ 1.5304,  0.9952, -0.8663],
        [ 0.3556, -1.7313, -0.6063]])
tensor([[ 0.2090, -0.9569, -0.9208,  0.0335],
        [-1.0305, -1.5582, -0.5516,  0.8989],
        [ 0.4671,  0.4139, -0.1767, -0.3024]])
tensor([[-1.1105, -3.3737, -1.8051,  1.2078],
        [ 1.5752,  2.1064,  0.7348, -1.3609]])
tensor([[-1.1105, -3.3737, -1.8051,  1.2078],
        [ 1.5752,  2.1064,  0.7348, -1.3609]])
tensor([[-1.1105, -3.3737, -1.8051,  1.2078],
        [ 1.5752,  2.1064,  0.7348, -1.3609]])
tensor([[-1.1105, -3.3737, -1.8051,  1.2078],
        [ 1.5752,  2.1064,  0.7348, -1.3609]])


In [ ]:
import torch

# 공용함수, 삼각함수, 지수함수, 로그함수, 비교함수, 논리함수, 통계함수, 선형대수 함수 등
# 모두 tensor를 입력으로 받고 tensor를 출력함
a = torch.randn(2, 3)
print(a)    
print(torch.abs(a))        # 절댓값
print(torch.acos(a))       # 아크코사인
print(torch.asin(a))       # 아크사인
print(torch.atan(a))       # 아크탄젠트
print(torch.ceil(a))       # 올림
print(torch.clamp(a, min=0.0)) # 최소값 지정
print(torch.cos(a))        # 코사인
print(torch.cosh(a))       # 쌍곡코사인
print(torch.exp(a))        # 지수함수
print(torch.floor(a))      # 내림
print(torch.log(a))        # 자연로그
print(torch.log10(a))      # 상용로그
print(torch.log2(a))       # 이진로그
print(torch.neg(a))        # 음수
print(torch.reciprocal(a)) # 역수
print(torch.round(a))      # 반올림
print(torch.rsqrt(a))      # 역수의 제곱근
print(torch.sign(a))       # 부호
print(torch.sin(a))        # 사인
print(torch.sinh(a))       # 쌍곡사인
print(torch.sqrt(a))       # 제곱근
print(torch.tan(a))        # 탄젠트
print(torch.tanh(a))       # 쌍곡탄젠트
print(torch.trunc(a))      # 정수부분
print(torch.eq(a, 0.0))    # 요소별 동일여부
print(torch.ge(a, 0.0))    # 요소별 크거나 같은지 여부
print(torch.gt(a, 0.0))    # 요소별 큰지 여부
print(torch.le(a, 0.0))    # 요소별 작거나 같은지 여부
print(torch.lt(a, 0.0))    # 요소별 작은지 여부
print(torch.ne(a, 0.0))    # 요소별 같지 않은지 여부
print(torch.all(a))        # 모든 요소가 참인지 여부
print(torch.any(a))        # 하나 이상의 요소가 참인지 여부
print(torch.argmax(a))     # 가장 큰 요소의 인덱스
print(torch.argmin(a))     # 가장 작은 요소의 인덱스
print(torch.max(a))        # 가장 큰 요소
print(torch.min(a))        # 가장 작은 요소
print(torch.mean(a))       # 평균
print(torch.median(a))     # 중앙값
print(torch.mode(a))       # 최빈값
print(torch.std(a))        # 표준편차
print(torch.var(a))        # 분산
print(torch.sum(a))        # 합 
print(torch.prod(a))       # 곱
print(torch.cumsum(a, dim=0)) # 누적합
print(torch.cumprod(a, dim=0))# 누적곱
print(torch.sort(a, dim=0))   # 정렬
print(torch.argsort(a, dim=0))# 정렬된 인덱스
print(torch.unique(a))        # 중복제거
print(torch.where(a>0, a, -a))# 조건에 따라 값 선택
print(torch.nonzero(a))      # 0이 아닌 요소의 인덱스
         

tensor([[ 0.1043, -0.5544,  1.0184],
        [ 0.8118,  0.4590, -0.9481]])
tensor([[0.1043, 0.5544, 1.0184],
        [0.8118, 0.4590, 0.9481]])
tensor([[1.4663, 2.1584,    nan],
        [0.6235, 1.0939, 2.8180]])
tensor([[ 0.1045, -0.5876,     nan],
        [ 0.9473,  0.4769, -1.2472]])
tensor([[ 0.1039, -0.5062,  0.7945],
        [ 0.6819,  0.4303, -0.7588]])
tensor([[1., -0., 2.],
        [1., 1., -0.]])
tensor([[0.1043, 0.0000, 1.0184],
        [0.8118, 0.4590, 0.0000]])
tensor([[0.9946, 0.8502, 0.5248],
        [0.6882, 0.8965, 0.5832]])
tensor([[1.0054, 1.1576, 1.5649],
        [1.3481, 1.1072, 1.4841]])
tensor([[1.1100, 0.5744, 2.7686],
        [2.2521, 1.5825, 0.3875]])
tensor([[ 0., -1.,  1.],
        [ 0.,  0., -1.]])
tensor([[-2.2603,     nan,  0.0182],
        [-0.2084, -0.7787,     nan]])
tensor([[-0.9816,     nan,  0.0079],
        [-0.0905, -0.3382,     nan]])
tensor([[-3.2609,     nan,  0.0262],
        [-0.3007, -1.1234,     nan]])
tensor([[-0.1043,  0.5544, -1.0184],
 

In [5]:
import torch

# 논리함수, 텐서 출력
a = torch.randint(9, (2, 3))
b = torch.randint(9, (2, 3))
print("-"*20)
c = a.logical_and(b) # 요소별 논리 AND
print(c)
c = a.logical_or(b)  # 요소별 논리 OR
print(c)
c = c.logical_not()  # 요소별 논리 NOT  
print(c)

--------------------
tensor([[False,  True,  True],
        [ True, False,  True]])
tensor([[False,  True,  True],
        [ True, False,  True]])
tensor([[ True, False, False],
        [False,  True, False]])


In [ ]:
import torch

# 텐서 변형 함수
a = torch.randn(2, 3)
print(a)

print(torch.flatten(a))      # 다차원 텐서를 1-D tensor로 변환
print(torch.reshape(a, (3,2))) # 텐서의 shape 변경
print(torch.transpose(a, 0, 1)) # 텐서의 차원 교환
print(torch.t(a))            # 2-D tensor의 전치행렬
print(torch.unsqueeze(a, 0)) # 지정한 위치에 차원 추가
print(torch.unsqueeze(a, 1)) # 지정한 위치에 차원 추가
print(torch.unsqueeze(a, 2)) # 지정한 위치에 차원 추가
print(torch.squeeze(a))      # 크기가 1인 차원 제거
print(torch.squeeze(torch.unsqueeze(a, 0))) # 크기가 1인 차원 제거


tensor([[ 0.2330, -1.2627,  0.3231],
        [ 0.7488, -0.6954,  0.3175]])
tensor([ 0.2330, -1.2627,  0.3231,  0.7488, -0.6954,  0.3175])
tensor([[ 0.2330, -1.2627],
        [ 0.3231,  0.7488],
        [-0.6954,  0.3175]])
tensor([[ 0.2330,  0.7488],
        [-1.2627, -0.6954],
        [ 0.3231,  0.3175]])
tensor([[ 0.2330,  0.7488],
        [-1.2627, -0.6954],
        [ 0.3231,  0.3175]])
tensor([[[ 0.2330, -1.2627,  0.3231],
         [ 0.7488, -0.6954,  0.3175]]])
tensor([[[ 0.2330, -1.2627,  0.3231]],

        [[ 0.7488, -0.6954,  0.3175]]])
tensor([[[ 0.2330],
         [-1.2627],
         [ 0.3231]],

        [[ 0.7488],
         [-0.6954],
         [ 0.3175]]])
tensor([[ 0.2330, -1.2627,  0.3231],
        [ 0.7488, -0.6954,  0.3175]])
tensor([[ 0.2330, -1.2627,  0.3231],
        [ 0.7488, -0.6954,  0.3175]])


In [7]:
import torch

# 텐서 결합 함수 cat
a = torch.randint(9, (2, 3))
print(a)

print("-"*20)
b = torch.cat([a, a], dim=0)  # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)
b = torch.cat([a, a], dim=1) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)

tensor([[3, 4, 2],
        [6, 2, 8]])
--------------------
tensor([[3, 4, 2],
        [6, 2, 8],
        [3, 4, 2],
        [6, 2, 8]])
torch.Size([4, 3])
--------------------
tensor([[3, 4, 2, 3, 4, 2],
        [6, 2, 8, 6, 2, 8]])
torch.Size([2, 6])
--------------------


In [8]:
import torch

# 텐서 결합 함수 stack
a = torch.randint(9, (3,4))
print(a)
print(a.shape)
print("-"*20)
b = torch.stack([a, a], dim=0) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)
b = torch.stack([a, a], dim=1) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)
b = torch.stack([a, a], dim=2) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)

tensor([[5, 8, 6, 0],
        [6, 0, 3, 5],
        [7, 6, 6, 4]])
torch.Size([3, 4])
--------------------
tensor([[[5, 8, 6, 0],
         [6, 0, 3, 5],
         [7, 6, 6, 4]],

        [[5, 8, 6, 0],
         [6, 0, 3, 5],
         [7, 6, 6, 4]]])
torch.Size([2, 3, 4])
--------------------
tensor([[[5, 8, 6, 0],
         [5, 8, 6, 0]],

        [[6, 0, 3, 5],
         [6, 0, 3, 5]],

        [[7, 6, 6, 4],
         [7, 6, 6, 4]]])
torch.Size([3, 2, 4])
--------------------
tensor([[[5, 5],
         [8, 8],
         [6, 6],
         [0, 0]],

        [[6, 6],
         [0, 0],
         [3, 3],
         [5, 5]],

        [[7, 7],
         [6, 6],
         [6, 6],
         [4, 4]]])
torch.Size([3, 4, 2])
--------------------


In [14]:
import torch

# tensor가 아닌 Python 기본 타입을 출력하는 경우
a = torch.tensor([3.5])
print(a)

# 스칼라 텐서의 값을 Python 기본 타입으로 반환 
print(a.item())  

#크기/차원 정보
print(a.size()) # torch.Size([1])
print(a.numel()) # 1, 텐서의 모든 요소 개수

# 전체 동등성 검사, 결과는 bool
b = torch.tensor([2.5])
print(a.equal(b))

# 요소별 동등성 검사, 결과는 tensor
print(a == b)      # tensor([False])


tensor([3.5000])
3.5
torch.Size([1])
1
False
tensor([False])


In [15]:
# 일부 검사함수
a = torch.randint(9, (2, 3))
print(a)   
b = a.is_floating_point() # 실수형 여부
print(b)
b = a.is_complex()       # 복소수형 여부
print(b)
b = a.is_same_size(a)    # 동일한 shape인지 여부
print(b)    
b = a.is_contiguous()    # 메모리상에 연속적으로 저장되어 있는지 여부
print(b) 

tensor([[6, 8, 2],
        [7, 0, 1]])
False
False
True
True


In [ ]:
a = torch.rand((2, 3))
print(a)

b = a.norm(p=2, dim=0) # 열벡터의 L2 norm 계산
print(b)
b = a.norm(p=2, dim=1) # 행벡터의 L2 norm 계산
print(b)

tensor([[0.6001, 0.4721, 0.9981],
        [0.1062, 0.0771, 0.6550]])
tensor([0.6094, 0.4784, 1.1938])
tensor([1.2567, 0.6680])


In [17]:
from sklearn.preprocessing import StandardScaler

X = torch.randn(5, 3).numpy() # 5개의 샘플과 3개의 특성
y = torch.randn(5).numpy()    # 5개의 샘플에 대한 타겟 값

# X에 적용할 scaler 객체 생성
scaler = StandardScaler().fit(X)
# y에 적용할 scaler 객체 생성
scaler_y = StandardScaler().fit(y.reshape(-1, 1))
# X에 transform 적용
X_scaled = scaler.transform(X)
# y에 transform 적용
y_scaled = scaler_y.transform(y.reshape(-1, 1)) 




In [18]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

mm = MinMaxScaler()
a = torch.rand((2,3))
print(a)
b = mm.fit_transform(a)
print(b)

norm = Normalizer(norm='l2')
a = torch.rand((2,3))
print(a)
b = norm.fit_transform(a)
print(b)
print(torch.norm(torch.tensor(b), p=2, dim=1))  # 행벡터의 L2 norm 계산, 모두 1.0이 나옴


tensor([[0.9652, 0.1775, 0.4340],
        [0.4004, 0.9515, 0.5338]])
[[1. 0. 0.]
 [0. 1. 1.]]
tensor([[0.7945, 0.4032, 0.8754],
        [0.2081, 0.1681, 0.5706]])
[[0.6360772  0.32276872 0.7008753 ]
 [0.33024856 0.26670748 0.9054297 ]]
tensor([1., 1.])


In [19]:
from torch import nn

weight = torch.empty(3, 5)

# sigmoid
nn.init.xavier_normal_(weight)
print(weight)
nn.init.xavier_uniform_(weight)
print(weight)

# ReLU
nn.init.kaiming_normal_(weight, mode='fan_in', nonlinearity='relu')
print(weight)
nn.init.kaiming_uniform_(weight, mode='fan_in', nonlinearity='relu')
print(weight)

tensor([[ 0.6898,  0.6810,  0.4189, -0.4413,  0.1932],
        [-0.4704, -0.1546, -0.2401,  1.3012,  0.3067],
        [ 0.2017,  0.4894,  0.1515, -0.3606, -1.1360]])
tensor([[-0.4609,  0.5594,  0.2620, -0.4065, -0.1208],
        [-0.7889, -0.7115,  0.7230, -0.3857, -0.5172],
        [-0.3409,  0.2743, -0.0330, -0.7731,  0.3041]])
tensor([[-0.9444, -0.4362, -0.5706, -0.4035, -0.4431],
        [ 0.9654, -0.0454,  1.2910, -0.2830, -0.8608],
        [-1.3790,  0.7629, -0.8594,  0.0178,  0.3878]])
tensor([[-0.6204,  0.1156, -0.8824, -0.8385, -0.5180],
        [-0.7299,  0.0025,  0.4165, -0.4534,  0.6242],
        [ 0.0420, -0.8638, -0.2323,  0.9321, -0.8336]])


In [66]:
# Multiple Linear Regression
# 문제 정의 : y = a*x1 + b*x2 + c*x3 + noise
# 
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Training data generation
traing_data_size = 1000
X_train = torch.randn(traing_data_size, 3)
coef = torch.tensor([1., 10., 100.]).unsqueeze(1)
noise = torch.randn(traing_data_size, 1)
y_train = X_train.mm(coef) + noise
print("X_train.shape, y_train.shape")
print(X_train.shape, y_train.shape)
      
# Test data generation,
# test1, test2 두 종류의 테스트 데이터 생성
# 각각 다른 분포를 가진 테스트 데이터도 잘 예측하는지 확인하기 위함
test_data_size = 200
X_test1 = torch.randn(test_data_size, 3)
y_test1 = X_test1.mm(coef)
X_test2 = torch.randn(test_data_size, 3) + 10.0
y_test2 = X_test2.mm(coef)
print("X_test1.shape, y_test1.shape, X_test2.shape, y_test2.shape") 
print(X_test1.shape, y_test1.shape, X_test2.shape, y_test2.shape)   

# 데이터 로더 정의
train_dataset = TensorDataset(X_train, y_train)
train_dataloader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test1_dataset = TensorDataset(X_test1, y_test1)
test1_dataloader = DataLoader(test1_dataset, batch_size=16, shuffle=False)
test2_dataset = TensorDataset(X_test2, y_test2)
test2_dataloader = DataLoader(test2_dataset, batch_size=16, shuffle=False)
print(len(train_dataloader), len(test1_dataloader), len(test2_dataloader))

# 모델 정의
class MultipleLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        in_size, out_size = len(coef), 1
        self.linear = nn.Linear(in_size, out_size)  # 입력 특성 3개, 출력 특성 1개
        print(self.linear.weight)
        print(self.linear.bias)

    def forward(self, x):
        return self.linear(x)

model = MultipleLinearRegressionModel()
print(model)

# 손실함수 정의
criterion = nn.MSELoss()

# 옵티마이저 정의
optimizer = optim.SGD(model.parameters(), lr=0.01)

# 학습 함수 정의
def train(model, dataloader):
    model.train()
    total_loss = 0.0
    for inputs, targets in dataloader:
        optimizer.zero_grad()           # 옵티마이저 초기화
        outputs = model(inputs)         # 모델에 입력 데이터 전달하여 출력 계산
        loss = criterion(outputs, targets) # 손실함수 계산
        loss.backward()                 # 역전파 수행하여 그래디언트 계산
        optimizer.step()                # 옵티마이저 스텝 수행하여 모델 파라미터 업데이트
        total_loss += loss.item() * inputs.size(dim=0) # 배치 손실 합산
        
    avg_loss = total_loss / len(dataloader.dataset) # 평균 손실 계산
    return avg_loss

# 모델 학습
print("===================== Training the model")
num_epochs = 20
for epoch in range(num_epochs):
    train_loss = train(model, train_dataloader)
    print(f"Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}")

print(model.linear.weight, model.linear.bias)

# 모델 평가
def evaluate(model, dataloader):
    model.eval()
    total_loss = 0.0
    with torch.no_grad():  # 평가 시에는 그래디언트 계산을 하지 않음
        for inputs, targets in dataloader:
            outputs = model(inputs)         # 모델에 입력 데이터 전달하여 출력 계산
            loss = criterion(outputs, targets) # 손실함수 계산
            total_loss += loss.item() * inputs.size(dim=0) # 배치 손실 합산
            
    avg_loss = total_loss / len(dataloader.dataset) # 평균 손실 계산
    return avg_loss

print("===================== Evaluating on Test1 and Test2 datasets")
test1_loss = evaluate(model, test1_dataloader)
print(f"Test1 평균 Loss: {test1_loss:.4f}")
test2_loss = evaluate(model, test2_dataloader)
print(f"Test2 평균 Loss: {test2_loss:.4f}")

print("=================== coef 차이")
c = model(torch.eye(len(coef)).float())
print(coef-c)

X_train.shape, y_train.shape
torch.Size([1000, 3]) torch.Size([1000, 1])
X_test1.shape, y_test1.shape, X_test2.shape, y_test2.shape
torch.Size([200, 3]) torch.Size([200, 1]) torch.Size([200, 3]) torch.Size([200, 1])
63 13 13
Parameter containing:
tensor([[-0.1364, -0.5050,  0.3335]], requires_grad=True)
Parameter containing:
tensor([-0.3651], requires_grad=True)
MultipleLinearRegressionModel(
  (linear): Linear(in_features=3, out_features=1, bias=True)
)
===================== Training the model
Epoch 1/20, Train Loss: 3697.1049
Epoch 2/20, Train Loss: 330.6601
Epoch 3/20, Train Loss: 30.6050
Epoch 4/20, Train Loss: 3.6997
Epoch 5/20, Train Loss: 1.2268
Epoch 6/20, Train Loss: 0.9945
Epoch 7/20, Train Loss: 0.9726
Epoch 8/20, Train Loss: 0.9716
Epoch 9/20, Train Loss: 0.9717
Epoch 10/20, Train Loss: 0.9717
Epoch 11/20, Train Loss: 0.9715
Epoch 12/20, Train Loss: 0.9711
Epoch 13/20, Train Loss: 0.9709
Epoch 14/20, Train Loss: 0.9711
Epoch 15/20, Train Loss: 0.9718
Epoch 16/20, Train Loss

In [67]:
# https://tutorials.pytorch.kr/beginner/basics/data_tutorial.html 따라해 보기

import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

# data 다운로드
traing_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

# 데이터 로더 정의
# 모델 정의
# 손실 함수 정의
# 옵티마이저 정의
# 모델 학습
# 모델 평가
