In [2]:
import numpy as np

M = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f"M=\n{M}")
[ [row[i] for row in M] for i in range(len(M[0]))]

M.shape





M=
[[1 2 3]
 [4 5 6]]


(2, 3)

In [11]:
import numpy as np
import torch 
A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])   

U, S, Vt = np.linalg.svd(A, full_matrices=False)
print(f"U=\n{U}\nS=\n{S}\nVt=\n{Vt}")
A = torch.from_numpy(A).to(torch.float64)
U, S, Vt = torch.linalg.svd(A, full_matrices=False)
print(f"U=\n{U}\nS=\n{S}\nVt=\n{Vt}")

U=
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
S=
[1.68481034e+01 1.06836951e+00 3.35890790e-16]
Vt=
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
U=
tensor([[-0.2148,  0.8872,  0.4082],
        [-0.5206,  0.2496, -0.8165],
        [-0.8263, -0.3879,  0.4082]], dtype=torch.float64)
S=
tensor([1.6848e+01, 1.0684e+00, 3.3589e-16], dtype=torch.float64)
Vt=
tensor([[-0.4797, -0.5724, -0.6651],
        [-0.7767, -0.0757,  0.6253],
        [-0.4082,  0.8165, -0.4082]], dtype=torch.float64)


In [8]:
import numpy as np

list(range(2))
number_matrix = np.array([[4, -2],
                  [1,  1]])

coefficients = np.poly(number_matrix)
print(coefficients)

[ 1. -5.  6.]


In [ ]:
import numpy as np

# null space 구하기
A = np.array([[1, 2, 3],
              [2, 4, 6]])  # rank = 1인 행렬

U, s, Vt = np.linalg.svd(A)
print(f"U={U}")
print(f"s={s}")
print(f"Vt={Vt}")

for i, row in enumerate(Vt):
    print(f"v_{i+1}^T = {row}")
tol = 1e-15
rank = np.sum(s > tol)
print(rank)
V = Vt[rank:, :].T
print(V)
A@V
# Eigenvalue is 1.0 and eigenvector corresponding to 1.0 is [1. 0. 0.]
# Eigenvalue is 3.0 and eigenvector corresponding to 3.0 is [0. 1. 0.]
# Eigenvalue is 2.0 and eigenvector corresponding to 2.0 is [0. 0. 1.]
# Eigenvalue is 3.0000000000000018 and eigenvector corresponding to 3.0000000000000018 is [-0.  0. -1.]
# Eigenvalue is 1.999999999999998 and eigenvector corresponding to 1.999999999999998 is [-1.  0. -0.]
# Eigenvalue is 1.0000000000000002 and eigenvector corresponding to 1.0000000000000002 is [-0.  1. -0.]

U=[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
s=[8.36660027e+00 5.61733355e-16]
Vt=[[-0.26726124 -0.53452248 -0.80178373]
 [ 0.94491118 -0.30854944 -0.10927077]
 [-0.18898224 -0.78681825  0.58753958]]
v_1^T = [-0.26726124 -0.53452248 -0.80178373]
v_2^T = [ 0.94491118 -0.30854944 -0.10927077]
v_3^T = [-0.18898224 -0.78681825  0.58753958]
1
[[ 0.94491118 -0.18898224]
 [-0.30854944 -0.78681825]
 [-0.10927077  0.58753958]]


array([[ 2.22044605e-16, -2.22044605e-16],
       [ 4.44089210e-16, -4.44089210e-16]])

In [26]:
import numpy as np

def svd_vs_eigen_general():
    """일반적인 정사각 행렬에서 SVD vs Eigendecomposition"""
    
    # 일반적인 비대칭 정사각 행렬
    A = np.array([[1, 2], 
                  [3, 4]])
    
    print("=== 일반적인 정사각 행렬 ===")
    print("A =")
    print(A)
    
    # SVD
    U, s, Vh = np.linalg.svd(A)
    print(f"\nSVD:")
    print(f"U (left singular vectors):\n{U}")
    print(f"Singular values: {s}")
    print(f"V^T (right singular vectors):\n{Vh}")
    
    # Eigendecomposition
    eigenvals, eigenvecs = np.linalg.eig(A)
    print(f"\nEigendecomposition:")
    print(f"Eigenvalues: {eigenvals}")
    print(f"Eigenvectors:\n{eigenvecs}")
    
    # 비교
    print(f"\n=== 비교 ===")
    print(f"Singular vectors와 eigenvectors가 같은가?")
    print(f"U와 eigenvectors: {np.allclose(np.abs(U), np.abs(eigenvecs))}")
    print(f"V^T와 eigenvectors: {np.allclose(np.abs(Vh), np.abs(eigenvecs.T))}")
    
    print(f"\nSingular values와 eigenvalues가 같은가?")
    print(f"s: {s}")
    print(f"eigenvals: {eigenvals}")
    print(f"같은가? {np.allclose(s, np.abs(eigenvals))}")

svd_vs_eigen_general()

=== 일반적인 정사각 행렬 ===
A =
[[1 2]
 [3 4]]

SVD:
U (left singular vectors):
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
V^T (right singular vectors):
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

Eigendecomposition:
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

=== 비교 ===
Singular vectors와 eigenvectors가 같은가?
U와 eigenvectors: False
V^T와 eigenvectors: False

Singular values와 eigenvalues가 같은가?
s: [5.4649857  0.36596619]
eigenvals: [-0.37228132  5.37228132]
같은가? False


In [31]:
number_matrix1 = [[1, 2, 3],
                                  [4, 5, 6]]
number_matrix2 = [[1, 2],
                                  [3, 4],
                                  [5, 6]]
# TODO : einsum을 활용하여 두 행렬의 곱을 계산하는 코드를 완성하세요.
mid1 = np.einsum('ik, kj -> ij', number_matrix1, number_matrix2)
# TODO : einsum을 활용하여 행렬의 대각성분의 합을 계산하는 코드를 완성하세요.
answer1 = np.einsum('ii -> ', mid1)
print(answer1)

86
