In [4]:
import torch

In [ ]:
# 0-D tensor
scalar = torch.tensor(3)   
print(scalar)       # tensor(3)
print(scalar.shape) # torch.Size([])
print(scalar.ndim)  # 0
print(scalar.dtype) # torch.int64

scalar2 = torch.randn(10).sum()
print(scalar2)       # tensor(-0.6778)
print(scalar2.shape) # torch.Size([])
print(scalar2.ndim)  # 0
print(scalar2.dtype) # torch.float32

a = torch.rand((3,4,5))
print(a)
scalar3 = torch.norm(a)
print(scalar3)       # tensor(4.4621)
print(scalar3.shape) # torch.Size([])
print(scalar3.ndim)  # 0
print(scalar3.dtype) # torch.float32

tensor(3)
torch.Size([])
0
torch.int64
tensor(-3.8736)
torch.Size([])
0
torch.float32
tensor([[[0.6464, 0.2190, 0.3491, 0.1715, 0.6927],
         [0.5851, 0.8262, 0.7804, 0.0249, 0.2472],
         [0.7990, 0.6928, 0.7007, 0.9647, 0.5964],
         [0.3987, 0.9602, 0.1992, 0.3600, 0.0203]],

        [[0.9545, 0.3374, 0.1573, 0.5573, 0.6754],
         [0.3582, 0.1536, 0.7443, 0.3852, 0.6371],
         [0.0181, 0.8723, 0.5822, 0.3664, 0.6135],
         [0.0846, 0.2743, 0.4268, 0.8712, 0.1239]],

        [[0.0787, 0.8582, 0.8458, 0.6987, 0.9896],
         [0.4355, 0.4469, 0.0590, 0.6033, 0.0257],
         [0.4188, 0.2952, 0.4162, 0.6849, 0.6183],
         [0.0276, 0.8214, 0.0886, 0.9776, 0.7972]]])
tensor(4.4621)
torch.Size([])
0
torch.float32


In [12]:
# 1-D tensor
vector1 = torch.tensor([1,2,3]) # 0-D tensor가 1,2,3 인 배열
print(vector1)       # tensor([1, 2, 3])
print(vector1.shape) # torch.Size([3])
print(vector1.ndim)  # 1
print(vector1.dtype) # torch.int64

vector2 = torch.randint(5, [1]) # 0-D tensor가 1개인 배열
print(vector2)       # tensor([3]), 0-D 텐서인 tensor(3)과 다름
print(vector2.shape) # torch.Size([1])
print(vector2.ndim)  # 1
print(vector2.dtype) # torch.int64

tensor([1, 2, 3])
torch.Size([3])
1
torch.int64
tensor([4])
torch.Size([1])
1
torch.int64


In [11]:
# 2-D tensor
matrix1 = torch.zeros(3, 4) # 1-D tensor가 3개인 배열
print(matrix1)
print(matrix1.size()) # torch.Size([3, 4])
print(matrix1.dim())  # 2
print(matrix1.dtype)  # torch.float32

matrix2 = torch.eye(4, dtype=torch.double)  # 1-D tensor가 4개인 배열
print(matrix2)
print(matrix2.size()) # torch.Size([4, 4])
print(matrix2.dim())  # 2
print(matrix2.dtype)  # torch.float64

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
2
torch.float32
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=torch.float64)
torch.Size([4, 4])
2
torch.float64


In [16]:
a = torch.randint(10, (2,3,4))
print(a)

# 전체 element 더하여 스칼라 텐서 생성됨, 결과는 0-D tensor
result = a.sum()
print(result)

# dim-0차원 2개의 배열을 더함, 스칼라 탠서로 변하면서 차원이 사라짐 => 결과는 (3,4) shape의 탠서
result = a.sum(dim=0)
print(result)

# dim-1차원 3개의 배열을 더함, 스칼라 텐서로 변하면서 해당 차원이 사라짐 => 결과는 (2,4) shape의 탠서
result = a.sum(dim=1)
print(result)

# dim-2차원 4개의 배열을 더함, 스칼라 텐서로 변하면서 해당 차원이 사라짐 => 결과는 (2,3) shape의 탠서
result = a.sum(dim=2)
print(result)

result = a.sum(dim=-1)
print(result)
result = a.sum(dim=-2)
print(result)
result = a.sum(dim=-3)
print(result)
                

tensor([[[4, 3, 4, 3],
         [5, 0, 1, 3],
         [3, 6, 8, 6]],

        [[5, 3, 2, 1],
         [1, 5, 0, 4],
         [2, 0, 1, 6]]])
tensor(76)
tensor([[ 9,  6,  6,  4],
        [ 6,  5,  1,  7],
        [ 5,  6,  9, 12]])
tensor([[12,  9, 13, 12],
        [ 8,  8,  3, 11]])
tensor([[14,  9, 23],
        [11, 10,  9]])
tensor([[14,  9, 23],
        [11, 10,  9]])
tensor([[12,  9, 13, 12],
        [ 8,  8,  3, 11]])
tensor([[ 9,  6,  6,  4],
        [ 6,  5,  1,  7],
        [ 5,  6,  9, 12]])
