In [2]:
import numpy as np

M = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f"M=\n{M}")
[ [row[i] for row in M] for i in range(len(M[0]))]

M.shape





M=
[[1 2 3]
 [4 5 6]]


(2, 3)

In [11]:
import numpy as np
import torch 
A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])   

U, S, Vt = np.linalg.svd(A, full_matrices=False)
print(f"U=\n{U}\nS=\n{S}\nVt=\n{Vt}")
A = torch.from_numpy(A).to(torch.float64)
U, S, Vt = torch.linalg.svd(A, full_matrices=False)
print(f"U=\n{U}\nS=\n{S}\nVt=\n{Vt}")

U=
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
S=
[1.68481034e+01 1.06836951e+00 3.35890790e-16]
Vt=
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
U=
tensor([[-0.2148,  0.8872,  0.4082],
        [-0.5206,  0.2496, -0.8165],
        [-0.8263, -0.3879,  0.4082]], dtype=torch.float64)
S=
tensor([1.6848e+01, 1.0684e+00, 3.3589e-16], dtype=torch.float64)
Vt=
tensor([[-0.4797, -0.5724, -0.6651],
        [-0.7767, -0.0757,  0.6253],
        [-0.4082,  0.8165, -0.4082]], dtype=torch.float64)
