In [2]:
import torch

In [3]:
# 0-D tensor
scalar = torch.tensor(3)   
print(scalar)       # tensor(3)
print(scalar.shape) # torch.Size([])
print(scalar.ndim)  # 0
print(scalar.dtype) # torch.int64

scalar2 = torch.randn(10).sum()
print(scalar2)       # tensor(-0.6778)
print(scalar2.shape) # torch.Size([])
print(scalar2.ndim)  # 0
print(scalar2.dtype) # torch.float32

a = torch.rand((3,4,5))
print(a)
scalar3 = torch.norm(a)
print(scalar3)       # tensor(4.4621)
print(scalar3.shape) # torch.Size([])
print(scalar3.ndim)  # 0
print(scalar3.dtype) # torch.float32

tensor(3)
torch.Size([])
0
torch.int64
tensor(-3.7479)
torch.Size([])
0
torch.float32
tensor([[[0.3227, 0.6038, 0.1653, 0.6338, 0.5041],
         [0.7668, 0.5388, 0.2554, 0.7792, 0.0989],
         [0.3374, 0.4285, 0.6398, 0.5788, 0.4403],
         [0.5941, 0.4049, 0.6454, 0.3858, 0.2043]],

        [[0.8329, 0.0767, 0.9926, 0.4648, 0.0053],
         [0.2595, 0.9331, 0.4218, 0.2538, 0.5858],
         [0.5930, 0.9648, 0.0621, 0.5225, 0.4520],
         [0.8334, 0.3594, 0.0120, 0.3373, 0.4600]],

        [[0.5776, 0.0787, 0.1733, 0.8930, 0.8688],
         [0.3109, 0.2024, 0.0287, 0.6448, 0.2256],
         [0.6729, 0.0285, 0.8323, 0.2145, 0.0516],
         [0.3094, 0.4027, 0.8591, 0.7421, 0.4169]]])
tensor(4.1051)
torch.Size([])
0
torch.float32


In [4]:
# 1-D tensor
vector1 = torch.tensor([1,2,3]) # 0-D tensor가 1,2,3 인 배열
print(vector1)       # tensor([1, 2, 3])
print(vector1.shape) # torch.Size([3])
print(vector1.ndim)  # 1
print(vector1.dtype) # torch.int64

vector2 = torch.randint(5, [1]) # 0-D tensor가 1개인 배열
print(vector2)       # tensor([3]), 0-D 텐서인 tensor(3)과 다름
print(vector2.shape) # torch.Size([1])
print(vector2.ndim)  # 1
print(vector2.dtype) # torch.int64

tensor([1, 2, 3])
torch.Size([3])
1
torch.int64
tensor([1])
torch.Size([1])
1
torch.int64


In [5]:
# 2-D tensor
matrix1 = torch.zeros(3, 4) # 1-D tensor가 3개인 배열
print(matrix1)
print(matrix1.size()) # torch.Size([3, 4])
print(matrix1.dim())  # 2
print(matrix1.dtype)  # torch.float32

matrix2 = torch.eye(4, dtype=torch.double)  # 1-D tensor가 4개인 배열
print(matrix2)
print(matrix2.size()) # torch.Size([4, 4])
print(matrix2.dim())  # 2
print(matrix2.dtype)  # torch.float64

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
2
torch.float32
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=torch.float64)
torch.Size([4, 4])
2
torch.float64


In [6]:
a = torch.randint(10, (2,3,4))
print(a)

# 전체 element 더하여 스칼라 텐서 생성됨, 결과는 0-D tensor
result = a.sum()
print(result)

# dim-0차원 2개의 배열을 더함, 스칼라 탠서로 변하면서 차원이 사라짐 => 결과는 (3,4) shape의 탠서
result = a.sum(dim=0)
print(result)

# dim-1차원 3개의 배열을 더함, 스칼라 텐서로 변하면서 해당 차원이 사라짐 => 결과는 (2,4) shape의 탠서
result = a.sum(dim=1)
print(result)

# dim-2차원 4개의 배열을 더함, 스칼라 텐서로 변하면서 해당 차원이 사라짐 => 결과는 (2,3) shape의 탠서
result = a.sum(dim=2)
print(result)

result = a.sum(dim=-1)
print(result)
result = a.sum(dim=-2)
print(result)
result = a.sum(dim=-3)
print(result)
                

tensor([[[6, 9, 1, 6],
         [6, 7, 2, 7],
         [8, 4, 3, 0]],

        [[0, 0, 3, 1],
         [3, 3, 3, 2],
         [4, 9, 2, 8]]])
tensor(97)
tensor([[ 6,  9,  4,  7],
        [ 9, 10,  5,  9],
        [12, 13,  5,  8]])
tensor([[20, 20,  6, 13],
        [ 7, 12,  8, 11]])
tensor([[22, 22, 15],
        [ 4, 11, 23]])
tensor([[22, 22, 15],
        [ 4, 11, 23]])
tensor([[20, 20,  6, 13],
        [ 7, 12,  8, 11]])
tensor([[ 6,  9,  4,  7],
        [ 9, 10,  5,  9],
        [12, 13,  5,  8]])


In [7]:
import torch

a = torch.randn(2, 3)
print(a)
b = torch.randn(2, 3)
print(b)
# 2-D tensor + 2-D tensor
print(a + b)
print(torch.add(a, b))
# 2-D tensor - 2-D tensor
print(a - b)
print(torch.sub(a, b))
# 2-D tensor * 2-D tensor
print(a * b)
print(torch.mul(a, b))
# 2-D tensor / 2-D tensor
print(a / b)
print(torch.div(a, b))  

tensor([[-1.5279, -0.7217, -0.0417],
        [ 0.6262, -0.8656,  1.1461]])
tensor([[ 0.4970, -0.3481,  0.4370],
        [ 1.0724,  0.6319,  1.2457]])
tensor([[-1.0309, -1.0699,  0.3954],
        [ 1.6986, -0.2337,  2.3918]])
tensor([[-1.0309, -1.0699,  0.3954],
        [ 1.6986, -0.2337,  2.3918]])
tensor([[-2.0249, -0.3736, -0.4787],
        [-0.4462, -1.4975, -0.0996]])
tensor([[-2.0249, -0.3736, -0.4787],
        [-0.4462, -1.4975, -0.0996]])
tensor([[-0.7593,  0.2513, -0.0182],
        [ 0.6715, -0.5470,  1.4277]])
tensor([[-0.7593,  0.2513, -0.0182],
        [ 0.6715, -0.5470,  1.4277]])
tensor([[-3.0742,  2.0731, -0.0953],
        [ 0.5839, -1.3698,  0.9201]])
tensor([[-3.0742,  2.0731, -0.0953],
        [ 0.5839, -1.3698,  0.9201]])


In [8]:
import torch

# 행렬곱
a = torch.randn(2, 3)
print(a)
b = torch.randn(3, 4)
print(b)
# 2-D tensor @ 2-D tensor
print(a @ b)
print(torch.matmul(a, b))
# 2-D tensor . 2-D tensor
print(a.mm(b))
print(torch.mm(a, b))   

tensor([[ 1.5304,  0.9952, -0.8663],
        [ 0.3556, -1.7313, -0.6063]])
tensor([[ 0.2090, -0.9569, -0.9208,  0.0335],
        [-1.0305, -1.5582, -0.5516,  0.8989],
        [ 0.4671,  0.4139, -0.1767, -0.3024]])
tensor([[-1.1105, -3.3737, -1.8051,  1.2078],
        [ 1.5752,  2.1064,  0.7348, -1.3609]])
tensor([[-1.1105, -3.3737, -1.8051,  1.2078],
        [ 1.5752,  2.1064,  0.7348, -1.3609]])
tensor([[-1.1105, -3.3737, -1.8051,  1.2078],
        [ 1.5752,  2.1064,  0.7348, -1.3609]])
tensor([[-1.1105, -3.3737, -1.8051,  1.2078],
        [ 1.5752,  2.1064,  0.7348, -1.3609]])


In [9]:
# 공용함수, 삼각함수, 지수함수, 로그함수, 비교함수, 논리함수, 통계함수, 선형대수 함수 등
a = torch.randn(2, 3)
print(a)    
print(torch.abs(a))        # 절댓값
print(torch.acos(a))       # 아크코사인
print(torch.asin(a))       # 아크사인
print(torch.atan(a))       # 아크탄젠트
print(torch.ceil(a))       # 올림
print(torch.clamp(a, min=0.0)) # 최소값 지정
print(torch.cos(a))        # 코사인
print(torch.cosh(a))       # 쌍곡코사인
print(torch.exp(a))        # 지수함수
print(torch.floor(a))      # 내림
print(torch.log(a))        # 자연로그
print(torch.log10(a))      # 상용로그
print(torch.log2(a))       # 이진로그
print(torch.neg(a))        # 음수
print(torch.reciprocal(a)) # 역수
print(torch.round(a))      # 반올림
print(torch.rsqrt(a))      # 역수의 제곱근
print(torch.sign(a))       # 부호
print(torch.sin(a))        # 사인
print(torch.sinh(a))       # 쌍곡사인
print(torch.sqrt(a))       # 제곱근
print(torch.tan(a))        # 탄젠트
print(torch.tanh(a))       # 쌍곡탄젠트
print(torch.trunc(a))      # 정수부분
print(torch.eq(a, 0.0))    # 요소별 동일여부
print(torch.ge(a, 0.0))    # 요소별 크거나 같은지 여부
print(torch.gt(a, 0.0))    # 요소별 큰지 여부
print(torch.le(a, 0.0))    # 요소별 작거나 같은지 여부
print(torch.lt(a, 0.0))    # 요소별 작은지 여부
print(torch.ne(a, 0.0))    # 요소별 같지 않은지 여부
print(torch.all(a))        # 모든 요소가 참인지 여부
print(torch.any(a))        # 하나 이상의 요소가 참인지 여부
print(torch.argmax(a))     # 가장 큰 요소의 인덱스
print(torch.argmin(a))     # 가장 작은 요소의 인덱스
print(torch.max(a))        # 가장 큰 요소
print(torch.min(a))        # 가장 작은 요소
print(torch.mean(a))       # 평균
print(torch.median(a))     # 중앙값
print(torch.mode(a))       # 최빈값
print(torch.std(a))        # 표준편차
print(torch.var(a))        # 분산
print(torch.sum(a))        # 합 
print(torch.prod(a))       # 곱
print(torch.cumsum(a, dim=0)) # 누적합
print(torch.cumprod(a, dim=0))# 누적곱
print(torch.sort(a, dim=0))   # 정렬
print(torch.argsort(a, dim=0))# 정렬된 인덱스
print(torch.unique(a))        # 중복제거
print(torch.where(a>0, a, -a))# 조건에 따라 값 선택
print(torch.nonzero(a))      # 0이 아닌 요소의 인덱스
         

tensor([[ 1.2716, -0.3512, -0.6278],
        [-0.2553,  0.9899,  1.5630]])
tensor([[1.2716, 0.3512, 0.6278],
        [0.2553, 0.9899, 1.5630]])
tensor([[   nan, 1.9297, 2.2496],
        [1.8290, 0.1426,    nan]])
tensor([[    nan, -0.3589, -0.6788],
        [-0.2582,  1.4282,     nan]])
tensor([[ 0.9044, -0.3377, -0.5606],
        [-0.2500,  0.7803,  1.0016]])
tensor([[2., -0., -0.],
        [-0., 1., 2.]])
tensor([[1.2716, 0.0000, 0.0000],
        [0.0000, 0.9899, 1.5630]])
tensor([[0.2947, 0.9390, 0.8093],
        [0.9676, 0.5488, 0.0078]])
tensor([[1.9235, 1.0623, 1.2036],
        [1.0328, 1.5312, 2.4912]])
tensor([[3.5667, 0.7038, 0.5337],
        [0.7747, 2.6908, 4.7729]])
tensor([[ 1., -1., -1.],
        [-1.,  0.,  1.]])
tensor([[ 0.2403,     nan,     nan],
        [    nan, -0.0102,  0.4466]])
tensor([[ 0.1044,     nan,     nan],
        [    nan, -0.0044,  0.1939]])
tensor([[ 0.3467,     nan,     nan],
        [    nan, -0.0147,  0.6443]])
tensor([[-1.2716,  0.3512,  0.6278],


In [10]:
a = torch.randint(9, (2, 3))
b = torch.randint(9, (2, 3))
print("-"*20)
c = a.logical_and(b) # 요소별 논리 AND
print(c)
c = a.logical_or(b)  # 요소별 논리 OR
print(c)
c = c.logical_not()  # 요소별 논리 NOT  
print(c)

--------------------
tensor([[ True,  True,  True],
        [ True, False,  True]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [11]:
# 텐서 변형 함수
a = torch.randn(2, 3)
print(a)

print(torch.flatten(a))      # 다차원 텐서를 1-D tensor로 변환
print(torch.reshape(a, (3,2))) # 텐서의 shape 변경
print(torch.transpose(a, 0, 1)) # 텐서의 차원 교환
print(torch.t(a))            # 2-D tensor의 전치행렬
print(torch.unsqueeze(a, 0)) # 지정한 위치에 차원 추가
print(torch.unsqueeze(a, 1)) # 지정한 위치에 차원 추가
print(torch.unsqueeze(a, 2)) # 지정한 위치에 차원 추가
print(torch.squeeze(a))      # 크기가 1인 차원 제거
print(torch.squeeze(torch.unsqueeze(a, 0))) # 크기가 1인 차원 제거

tensor([[ 0.9742,  0.1250,  1.2679],
        [ 0.4075,  0.6993, -0.9395]])
tensor([ 0.9742,  0.1250,  1.2679,  0.4075,  0.6993, -0.9395])
tensor([[ 0.9742,  0.1250],
        [ 1.2679,  0.4075],
        [ 0.6993, -0.9395]])
tensor([[ 0.9742,  0.4075],
        [ 0.1250,  0.6993],
        [ 1.2679, -0.9395]])
tensor([[ 0.9742,  0.4075],
        [ 0.1250,  0.6993],
        [ 1.2679, -0.9395]])
tensor([[[ 0.9742,  0.1250,  1.2679],
         [ 0.4075,  0.6993, -0.9395]]])
tensor([[[ 0.9742,  0.1250,  1.2679]],

        [[ 0.4075,  0.6993, -0.9395]]])
tensor([[[ 0.9742],
         [ 0.1250],
         [ 1.2679]],

        [[ 0.4075],
         [ 0.6993],
         [-0.9395]]])
tensor([[ 0.9742,  0.1250,  1.2679],
        [ 0.4075,  0.6993, -0.9395]])
tensor([[ 0.9742,  0.1250,  1.2679],
        [ 0.4075,  0.6993, -0.9395]])


In [12]:
# 텐서 결합 함수 cat

a = torch.randint(9, (2, 3))
print(a)

print("-"*20)
b = torch.cat([a, a], dim=0)  # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)
b = torch.cat([a, a], dim=1) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)

tensor([[7, 8, 6],
        [0, 8, 8]])
--------------------
tensor([[7, 8, 6],
        [0, 8, 8],
        [7, 8, 6],
        [0, 8, 8]])
torch.Size([4, 3])
--------------------
tensor([[7, 8, 6, 7, 8, 6],
        [0, 8, 8, 0, 8, 8]])
torch.Size([2, 6])
--------------------


In [13]:
import torch

# 텐서 결합 함수 stack
a = torch.randint(9, (3,4))
print(a)
print(a.shape)
print("-"*20)
b = torch.stack([a, a], dim=0) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)
b = torch.stack([a, a], dim=1) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)
b = torch.stack([a, a], dim=2) # 지정한 차원의 크기를 증가시킴
print(b)
print(b.shape)
print("-"*20)

tensor([[3, 7, 6, 8],
        [0, 7, 0, 3],
        [3, 2, 6, 0]])
torch.Size([3, 4])
--------------------
tensor([[[3, 7, 6, 8],
         [0, 7, 0, 3],
         [3, 2, 6, 0]],

        [[3, 7, 6, 8],
         [0, 7, 0, 3],
         [3, 2, 6, 0]]])
torch.Size([2, 3, 4])
--------------------
tensor([[[3, 7, 6, 8],
         [3, 7, 6, 8]],

        [[0, 7, 0, 3],
         [0, 7, 0, 3]],

        [[3, 2, 6, 0],
         [3, 2, 6, 0]]])
torch.Size([3, 2, 4])
--------------------
tensor([[[3, 3],
         [7, 7],
         [6, 6],
         [8, 8]],

        [[0, 0],
         [7, 7],
         [0, 0],
         [3, 3]],

        [[3, 3],
         [2, 2],
         [6, 6],
         [0, 0]]])
torch.Size([3, 4, 2])
--------------------


In [14]:
# tensor가 아닌 Python 기본 타입을 출력하는 경우
a = torch.tensor([3.5])
print(a)
print(a.item())  # 스칼라 텐서의 값을 Python 기본 타입으로 반환 

#크기/차원 정보
print(a.shape) # torch.Size([1])
print(a.ndim)  # 1
print(a.dtype) # torch.float32  
print(a.numel()) # 1, 텐서의 모든 요소 개수

# 전체 동등성 검사
b = torch.tensor([2.5])
print(a.equal(b))  # False
print(a == b)      # tensor([False])


tensor([3.5000])
3.5
torch.Size([1])
1
torch.float32
1
False
tensor([False])


In [15]:
# 일부 검사함수
a = torch.randint(9, (2, 3))
print(a)   
b = a.is_floating_point() # 실수형 여부
print(b)
b = a.is_complex()       # 복소수형 여부
print(b)
b = a.is_same_size(a)    # 동일한 shape인지 여부
print(b)    
b = a.is_contiguous()    # 메모리상에 연속적으로 저장되어 있는지 여부
print(b) 

tensor([[6, 8, 2],
        [7, 0, 1]])
False
False
True
True


In [16]:
a = torch.rand((2, 3))
print(a)

b = a.norm(p=2, dim=0) # 열벡터의 L2 norm 계산
print(b)
b = a.norm(p=2, dim=1) # 행벡터의 L2 norm 계산
print(b)

tensor([[0.6001, 0.4721, 0.9981],
        [0.1062, 0.0771, 0.6550]])
tensor([0.6094, 0.4784, 1.1938])
tensor([1.2567, 0.6680])


In [17]:
from sklearn.preprocessing import StandardScaler

X = torch.randn(5, 3).numpy() # 5개의 샘플과 3개의 특성
y = torch.randn(5).numpy()    # 5개의 샘플에 대한 타겟 값

# X에 적용할 scaler 객체 생성
scaler = StandardScaler().fit(X)
# y에 적용할 scaler 객체 생성
scaler_y = StandardScaler().fit(y.reshape(-1, 1))
# X에 transform 적용
X_scaled = scaler.transform(X)
# y에 transform 적용
y_scaled = scaler_y.transform(y.reshape(-1, 1)) 




In [18]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

mm = MinMaxScaler()
a = torch.rand((2,3))
print(a)
b = mm.fit_transform(a)
print(b)

norm = Normalizer(norm='l2')
a = torch.rand((2,3))
print(a)
b = norm.fit_transform(a)
print(b)
print(torch.norm(torch.tensor(b), p=2, dim=1))  # 행벡터의 L2 norm 계산, 모두 1.0이 나옴


tensor([[0.9652, 0.1775, 0.4340],
        [0.4004, 0.9515, 0.5338]])
[[1. 0. 0.]
 [0. 1. 1.]]
tensor([[0.7945, 0.4032, 0.8754],
        [0.2081, 0.1681, 0.5706]])
[[0.6360772  0.32276872 0.7008753 ]
 [0.33024856 0.26670748 0.9054297 ]]
tensor([1., 1.])


In [19]:
from torch import nn

weight = torch.empty(3, 5)

# sigmoid
nn.init.xavier_normal_(weight)
print(weight)
nn.init.xavier_uniform_(weight)
print(weight)

# ReLU
nn.init.kaiming_normal_(weight, mode='fan_in', nonlinearity='relu')
print(weight)
nn.init.kaiming_uniform_(weight, mode='fan_in', nonlinearity='relu')
print(weight)

tensor([[ 0.6898,  0.6810,  0.4189, -0.4413,  0.1932],
        [-0.4704, -0.1546, -0.2401,  1.3012,  0.3067],
        [ 0.2017,  0.4894,  0.1515, -0.3606, -1.1360]])
tensor([[-0.4609,  0.5594,  0.2620, -0.4065, -0.1208],
        [-0.7889, -0.7115,  0.7230, -0.3857, -0.5172],
        [-0.3409,  0.2743, -0.0330, -0.7731,  0.3041]])
tensor([[-0.9444, -0.4362, -0.5706, -0.4035, -0.4431],
        [ 0.9654, -0.0454,  1.2910, -0.2830, -0.8608],
        [-1.3790,  0.7629, -0.8594,  0.0178,  0.3878]])
tensor([[-0.6204,  0.1156, -0.8824, -0.8385, -0.5180],
        [-0.7299,  0.0025,  0.4165, -0.4534,  0.6242],
        [ 0.0420, -0.8638, -0.2323,  0.9321, -0.8336]])
